Refactor for differences between Darwin and Linux

diff --git a/ensure_krb_ticket b/ensure_krb_ticket
--- a/ensure_krb_ticket
+++ b/ensure_krb_ticket
@@ -5,18 +5,28 @@ if [[ -z "$realm" ]]; then
     exit 1
 fi
 
-ticket=$(klist | grep "krbtgt/${realm}@${realm}" )
+ticket=$(klist 2>/dev/null | grep "krbtgt/${realm}@${realm}" )
 if [[ -z "$ticket" ]]; then
     kinit ${USER}@${realm}
-    exit $? 
+    exit $?
 else
-    expires=$(echo "$ticket" | cut -d ' ' -f 6-9 ) 
-    expires_epoch=$(date -j -f "%b %d %H:%M:%S %Y" "$expires" +"%s")
-    now_epoch=$(date +"%s")
-#    echo "expires: $expires_epoch  now: $now_epoch"
+    os_type=$(uname)
+    if [[ $os_type == "Darwin" ]]; then
+        expires=$(echo "$ticket" | cut -d ' ' -f 6-9 )
+        expires_epoch=$(date -j -f "%b %d %H:%M:%S %Y" "$expires" +"%s")
+        now_epoch=$(date +"%s")
+    #    echo "expires: $expires_epoch  now: $now_epoch"
+    elif [[ $os_type == "Linux" ]]; then
+        expires=$(echo "$ticket" | cut -d ' ' -f 4-5 )
+        expires_epoch=$(date -d "$expires" +"%s")
+        now_epoch=$(date +"%s")
+    else
+        echo "Can't determine OS type from 'uname'"
+        exit 2
+    fi
     if [[ $expires_epoch < $now_epoch ]]; then
         kinit ${USER}@${realm}
-        exit $? 
+        exit $?
     fi
     exit 0
 fi
